### ISSUE TITLE
合并请求

### ISSUE THREAD

**Issue by 2892211452** [Extrader-home/BirthdayReminder#1]
你好老哥，我是https://github.com/2892211452/birthdayBot 的作者。
有注意到你这边有重构了一遍这个生日提醒脚本，感觉做的挺不错的，有没有兴趣合并为一个项目，你提交这边的代码为pull request到我们的仓库，咱俩共同开发后序功能

**Comment by Extrader-home** [comment]
> 你好老哥，我是https://github.com/2892211452/birthdayBot 的作者。 有注意到你这边有重构了一遍这个生日提醒脚本，感觉做的挺不错的，有没有兴趣合并为一个项目，你提交这边的代码为pull request到我们的仓库，咱俩共同开发后序功能

可以的
